from django.urls import path
from . import views

urlpatterns = [
    path('', views.read, name='read'),
    path('alice_one', views.alice_one, name='alice_one'),
    path('alice_two', views.alice_two, name='alice_two'),
    path('alice_three', views.alice_three, name='alice_three'),
    path('alice_four', views.alice_four, name='alice_four'),
    path('alice_five', views.alice_five, name='alice_five'),
    path('alice_six', views.alice_six, name='alice_six'),
    path('alice_seven', views.alice_seven, name='alice_seven'),
    path('alice_eight', views.alice_eight, name='alice_eight'),
    path('alice_nine', views.alice_nine, name='alice_nine'),
    path('alice_ten', views.alice_ten, name='alice_ten'),
    path('alice_eleven', views.alice_eleven, name='alice_eleven'),
    path('alice_twelve', views.alice_twelve, name='alice_twelve'),
    path('glass_one', views.glass_one, name='glass_one'),
    path('glass_two', views.glass_two, name='glass_two'),
    path('glass_three', views.glass_three, name='glass_three'),
    path('glass_four', views.glass_four, name='glass_four'),
    path('glass_five', views.glass_five, name='glass_five'),
    path('glass_six', views.glass_six, name='glass_six'),
    path('glass_seven', views.glass_seven, name='glass_seven'),
    path('glass_eight', views.glass_eight, name='glass_eight'),
    path('glass_nine', views.glass_nine, name='glass_nine'),
    path('glass_ten', views.glass_ten, name='glass_ten'),
    path('glass_eleven', views.glass_eleven, name='glass_eleven'),
    path('treasure_one', views.treasure_one, name='treasure_one'),
    path('treasure_two', views.treasure_two, name='treasure_two'),
    path('treasure_three', views.treasure_three, name='treasure_three'),
    path('treasure_four', views.treasure_four, name='treasure_four'),
    path('treasure_five', views.treasure_five, name='treasure_five'),
    path('treasure_six', views.treasure_six, name='treasure_six'),
    path('peter_one', views.peter_one, name='peter_one'),
    path('peter_two', views.peter_two, name='peter_two'),
    path('peter_three', views.peter_three, name='peter_three'),
    path('peter_four', views.peter_four, name='peter_four'),
    path('peter_five', views.peter_five, name='peter_five'),
    path('peter_six', views.peter_six, name='peter_six'),
    ]